// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package openbook_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Place an order that shall take existing liquidity off of the book, not
// add a new order off the book.
//
// This type of order allows for instant token settlement for the taker.
type PlaceTakeOrder struct {
	Args *PlaceTakeOrderArgs

	// [0] = [WRITE, SIGNER] signer
	//
	// [1] = [WRITE, SIGNER] penaltyPayer
	//
	// [2] = [WRITE] market
	//
	// [3] = [] marketAuthority
	//
	// [4] = [WRITE] bids
	//
	// [5] = [WRITE] asks
	//
	// [6] = [WRITE] marketBaseVault
	//
	// [7] = [WRITE] marketQuoteVault
	//
	// [8] = [WRITE] eventHeap
	//
	// [9] = [WRITE] userBaseAccount
	//
	// [10] = [WRITE] userQuoteAccount
	//
	// [11] = [] oracleA
	//
	// [12] = [] oracleB
	//
	// [13] = [] tokenProgram
	//
	// [14] = [] systemProgram
	//
	// [15] = [SIGNER] openOrdersAdmin
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewPlaceTakeOrderInstructionBuilder creates a new `PlaceTakeOrder` instruction builder.
func NewPlaceTakeOrderInstructionBuilder() *PlaceTakeOrder {
	nd := &PlaceTakeOrder{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 16),
	}
	return nd
}

// SetArgs sets the "args" parameter.
func (inst *PlaceTakeOrder) SetArgs(args PlaceTakeOrderArgs) *PlaceTakeOrder {
	inst.Args = &args
	return inst
}

// SetSignerAccount sets the "signer" account.
func (inst *PlaceTakeOrder) SetSignerAccount(signer ag_solanago.PublicKey) *PlaceTakeOrder {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(signer).WRITE().SIGNER()
	return inst
}

// GetSignerAccount gets the "signer" account.
func (inst *PlaceTakeOrder) GetSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetPenaltyPayerAccount sets the "penaltyPayer" account.
func (inst *PlaceTakeOrder) SetPenaltyPayerAccount(penaltyPayer ag_solanago.PublicKey) *PlaceTakeOrder {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(penaltyPayer).WRITE().SIGNER()
	return inst
}

// GetPenaltyPayerAccount gets the "penaltyPayer" account.
func (inst *PlaceTakeOrder) GetPenaltyPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetMarketAccount sets the "market" account.
func (inst *PlaceTakeOrder) SetMarketAccount(market ag_solanago.PublicKey) *PlaceTakeOrder {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(market).WRITE()
	return inst
}

// GetMarketAccount gets the "market" account.
func (inst *PlaceTakeOrder) GetMarketAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetMarketAuthorityAccount sets the "marketAuthority" account.
func (inst *PlaceTakeOrder) SetMarketAuthorityAccount(marketAuthority ag_solanago.PublicKey) *PlaceTakeOrder {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(marketAuthority)
	return inst
}

// GetMarketAuthorityAccount gets the "marketAuthority" account.
func (inst *PlaceTakeOrder) GetMarketAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetBidsAccount sets the "bids" account.
func (inst *PlaceTakeOrder) SetBidsAccount(bids ag_solanago.PublicKey) *PlaceTakeOrder {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(bids).WRITE()
	return inst
}

// GetBidsAccount gets the "bids" account.
func (inst *PlaceTakeOrder) GetBidsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetAsksAccount sets the "asks" account.
func (inst *PlaceTakeOrder) SetAsksAccount(asks ag_solanago.PublicKey) *PlaceTakeOrder {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(asks).WRITE()
	return inst
}

// GetAsksAccount gets the "asks" account.
func (inst *PlaceTakeOrder) GetAsksAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetMarketBaseVaultAccount sets the "marketBaseVault" account.
func (inst *PlaceTakeOrder) SetMarketBaseVaultAccount(marketBaseVault ag_solanago.PublicKey) *PlaceTakeOrder {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(marketBaseVault).WRITE()
	return inst
}

// GetMarketBaseVaultAccount gets the "marketBaseVault" account.
func (inst *PlaceTakeOrder) GetMarketBaseVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetMarketQuoteVaultAccount sets the "marketQuoteVault" account.
func (inst *PlaceTakeOrder) SetMarketQuoteVaultAccount(marketQuoteVault ag_solanago.PublicKey) *PlaceTakeOrder {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(marketQuoteVault).WRITE()
	return inst
}

// GetMarketQuoteVaultAccount gets the "marketQuoteVault" account.
func (inst *PlaceTakeOrder) GetMarketQuoteVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetEventHeapAccount sets the "eventHeap" account.
func (inst *PlaceTakeOrder) SetEventHeapAccount(eventHeap ag_solanago.PublicKey) *PlaceTakeOrder {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(eventHeap).WRITE()
	return inst
}

// GetEventHeapAccount gets the "eventHeap" account.
func (inst *PlaceTakeOrder) GetEventHeapAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetUserBaseAccountAccount sets the "userBaseAccount" account.
func (inst *PlaceTakeOrder) SetUserBaseAccountAccount(userBaseAccount ag_solanago.PublicKey) *PlaceTakeOrder {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(userBaseAccount).WRITE()
	return inst
}

// GetUserBaseAccountAccount gets the "userBaseAccount" account.
func (inst *PlaceTakeOrder) GetUserBaseAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetUserQuoteAccountAccount sets the "userQuoteAccount" account.
func (inst *PlaceTakeOrder) SetUserQuoteAccountAccount(userQuoteAccount ag_solanago.PublicKey) *PlaceTakeOrder {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(userQuoteAccount).WRITE()
	return inst
}

// GetUserQuoteAccountAccount gets the "userQuoteAccount" account.
func (inst *PlaceTakeOrder) GetUserQuoteAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetOracleAAccount sets the "oracleA" account.
func (inst *PlaceTakeOrder) SetOracleAAccount(oracleA ag_solanago.PublicKey) *PlaceTakeOrder {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(oracleA)
	return inst
}

// GetOracleAAccount gets the "oracleA" account.
func (inst *PlaceTakeOrder) GetOracleAAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetOracleBAccount sets the "oracleB" account.
func (inst *PlaceTakeOrder) SetOracleBAccount(oracleB ag_solanago.PublicKey) *PlaceTakeOrder {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(oracleB)
	return inst
}

// GetOracleBAccount gets the "oracleB" account.
func (inst *PlaceTakeOrder) GetOracleBAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *PlaceTakeOrder) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *PlaceTakeOrder {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *PlaceTakeOrder) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(13)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *PlaceTakeOrder) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *PlaceTakeOrder {
	inst.AccountMetaSlice[14] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *PlaceTakeOrder) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(14)
}

// SetOpenOrdersAdminAccount sets the "openOrdersAdmin" account.
func (inst *PlaceTakeOrder) SetOpenOrdersAdminAccount(openOrdersAdmin ag_solanago.PublicKey) *PlaceTakeOrder {
	inst.AccountMetaSlice[15] = ag_solanago.Meta(openOrdersAdmin).SIGNER()
	return inst
}

// GetOpenOrdersAdminAccount gets the "openOrdersAdmin" account.
func (inst *PlaceTakeOrder) GetOpenOrdersAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(15)
}

func (inst PlaceTakeOrder) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_PlaceTakeOrder,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst PlaceTakeOrder) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *PlaceTakeOrder) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Args == nil {
			return errors.New("Args parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Signer is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.PenaltyPayer is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Market is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.MarketAuthority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Bids is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Asks is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.MarketBaseVault is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.MarketQuoteVault is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.EventHeap is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.UserBaseAccount is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.UserQuoteAccount is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.OracleA is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.OracleB is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[14] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[15] == nil {
			return errors.New("accounts.OpenOrdersAdmin is not set")
		}
	}
	return nil
}

func (inst *PlaceTakeOrder) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("PlaceTakeOrder")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Args", *inst.Args))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=16]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("          signer", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("    penaltyPayer", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("          market", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta(" marketAuthority", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("            bids", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("            asks", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta(" marketBaseVault", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("marketQuoteVault", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("       eventHeap", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("        userBase", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("       userQuote", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("         oracleA", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("         oracleB", inst.AccountMetaSlice.Get(12)))
						accountsBranch.Child(ag_format.Meta("    tokenProgram", inst.AccountMetaSlice.Get(13)))
						accountsBranch.Child(ag_format.Meta("   systemProgram", inst.AccountMetaSlice.Get(14)))
						accountsBranch.Child(ag_format.Meta(" openOrdersAdmin", inst.AccountMetaSlice.Get(15)))
					})
				})
		})
}

func (obj PlaceTakeOrder) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Args` param:
	err = encoder.Encode(obj.Args)
	if err != nil {
		return err
	}
	return nil
}
func (obj *PlaceTakeOrder) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Args`:
	err = decoder.Decode(&obj.Args)
	if err != nil {
		return err
	}
	return nil
}

// NewPlaceTakeOrderInstruction declares a new PlaceTakeOrder instruction with the provided parameters and accounts.
func NewPlaceTakeOrderInstruction(
	// Parameters:
	args PlaceTakeOrderArgs,
	// Accounts:
	signer ag_solanago.PublicKey,
	penaltyPayer ag_solanago.PublicKey,
	market ag_solanago.PublicKey,
	marketAuthority ag_solanago.PublicKey,
	bids ag_solanago.PublicKey,
	asks ag_solanago.PublicKey,
	marketBaseVault ag_solanago.PublicKey,
	marketQuoteVault ag_solanago.PublicKey,
	eventHeap ag_solanago.PublicKey,
	userBaseAccount ag_solanago.PublicKey,
	userQuoteAccount ag_solanago.PublicKey,
	oracleA ag_solanago.PublicKey,
	oracleB ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	openOrdersAdmin ag_solanago.PublicKey) *PlaceTakeOrder {
	return NewPlaceTakeOrderInstructionBuilder().
		SetArgs(args).
		SetSignerAccount(signer).
		SetPenaltyPayerAccount(penaltyPayer).
		SetMarketAccount(market).
		SetMarketAuthorityAccount(marketAuthority).
		SetBidsAccount(bids).
		SetAsksAccount(asks).
		SetMarketBaseVaultAccount(marketBaseVault).
		SetMarketQuoteVaultAccount(marketQuoteVault).
		SetEventHeapAccount(eventHeap).
		SetUserBaseAccountAccount(userBaseAccount).
		SetUserQuoteAccountAccount(userQuoteAccount).
		SetOracleAAccount(oracleA).
		SetOracleBAccount(oracleB).
		SetTokenProgramAccount(tokenProgram).
		SetSystemProgramAccount(systemProgram).
		SetOpenOrdersAdminAccount(openOrdersAdmin)
}
