// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package openbook_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Set market to expired before pruning orders and closing the market (only
// [`close_market_admin`](crate::state::Market::close_market_admin)).
type SetMarketExpired struct {

	// [0] = [SIGNER] closeMarketAdmin
	//
	// [1] = [WRITE] market
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetMarketExpiredInstructionBuilder creates a new `SetMarketExpired` instruction builder.
func NewSetMarketExpiredInstructionBuilder() *SetMarketExpired {
	nd := &SetMarketExpired{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetCloseMarketAdminAccount sets the "closeMarketAdmin" account.
func (inst *SetMarketExpired) SetCloseMarketAdminAccount(closeMarketAdmin ag_solanago.PublicKey) *SetMarketExpired {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(closeMarketAdmin).SIGNER()
	return inst
}

// GetCloseMarketAdminAccount gets the "closeMarketAdmin" account.
func (inst *SetMarketExpired) GetCloseMarketAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetMarketAccount sets the "market" account.
func (inst *SetMarketExpired) SetMarketAccount(market ag_solanago.PublicKey) *SetMarketExpired {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(market).WRITE()
	return inst
}

// GetMarketAccount gets the "market" account.
func (inst *SetMarketExpired) GetMarketAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst SetMarketExpired) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetMarketExpired,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetMarketExpired) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetMarketExpired) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.CloseMarketAdmin is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Market is not set")
		}
	}
	return nil
}

func (inst *SetMarketExpired) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetMarketExpired")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("closeMarketAdmin", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("          market", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj SetMarketExpired) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *SetMarketExpired) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewSetMarketExpiredInstruction declares a new SetMarketExpired instruction with the provided parameters and accounts.
func NewSetMarketExpiredInstruction(
	// Accounts:
	closeMarketAdmin ag_solanago.PublicKey,
	market ag_solanago.PublicKey) *SetMarketExpired {
	return NewSetMarketExpiredInstructionBuilder().
		SetCloseMarketAdminAccount(closeMarketAdmin).
		SetMarketAccount(market)
}
