// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package openbook_v2

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// StubOracleClose is the `stubOracleClose` instruction.
type StubOracleClose struct {

	// [0] = [SIGNER] owner
	//
	// [1] = [WRITE] oracle
	//
	// [2] = [WRITE] solDestination
	//
	// [3] = [] tokenProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewStubOracleCloseInstructionBuilder creates a new `StubOracleClose` instruction builder.
func NewStubOracleCloseInstructionBuilder() *StubOracleClose {
	nd := &StubOracleClose{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetOwnerAccount sets the "owner" account.
func (inst *StubOracleClose) SetOwnerAccount(owner ag_solanago.PublicKey) *StubOracleClose {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(owner).SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
func (inst *StubOracleClose) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetOracleAccount sets the "oracle" account.
func (inst *StubOracleClose) SetOracleAccount(oracle ag_solanago.PublicKey) *StubOracleClose {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(oracle).WRITE()
	return inst
}

// GetOracleAccount gets the "oracle" account.
func (inst *StubOracleClose) GetOracleAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetSolDestinationAccount sets the "solDestination" account.
func (inst *StubOracleClose) SetSolDestinationAccount(solDestination ag_solanago.PublicKey) *StubOracleClose {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(solDestination).WRITE()
	return inst
}

// GetSolDestinationAccount gets the "solDestination" account.
func (inst *StubOracleClose) GetSolDestinationAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *StubOracleClose) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *StubOracleClose {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *StubOracleClose) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst StubOracleClose) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_StubOracleClose,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst StubOracleClose) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *StubOracleClose) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Owner is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Oracle is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.SolDestination is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

func (inst *StubOracleClose) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("StubOracleClose")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("         owner", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("        oracle", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("solDestination", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("  tokenProgram", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj StubOracleClose) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *StubOracleClose) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewStubOracleCloseInstruction declares a new StubOracleClose instruction with the provided parameters and accounts.
func NewStubOracleCloseInstruction(
	// Accounts:
	owner ag_solanago.PublicKey,
	oracle ag_solanago.PublicKey,
	solDestination ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *StubOracleClose {
	return NewStubOracleCloseInstructionBuilder().
		SetOwnerAccount(owner).
		SetOracleAccount(oracle).
		SetSolDestinationAccount(solDestination).
		SetTokenProgramAccount(tokenProgram)
}
